name = "MPIArrays"
uuid = "c63b6952-658b-40a1-840c-e84f6adc5553"
version = "1.0.0"
authors = ["Andreas Feuerpfeil"]

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
MPI = "0.20.23"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
